import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import C1 from '../img/window-tinting-2.jpg'
import C2 from '../img/carousel-2.jpg'

import {
	GiShakingHands,
	GiAchievement,
	GiCombinationLock,
	GiThreeFriends,
	GiFactory,
	GiMetalDisc,
	
} from "react-icons/gi";
import {FcApproval} from 'react-icons/fc'
import { BsShieldCheck, BsPeople } from "react-icons/bs";
import { GrUserWorker, GrUnorderedList, GrDeliver } from "react-icons/gr";


import A1 from '../img/about-1.jpg'
import A2 from "../img/about-2.jpg";
import A3 from "../img/about-3.jpg";
import A4 from "../img/about-4.jpg";
import { AiFillPhone } from "react-icons/ai";
import { BsFillEnvelopeFill } from "react-icons/bs";
import {FiPhoneCall} from "react-icons/fi"
import Feature from '../img/why-us-img.png'
import S1 from '../img/service-1.jpg'
import S2 from "../img/service-2.jpg";
import S3 from "../img/service-3.jpg";
import S4 from "../img/image.jpg";
import S5 from "../img/image2.jpg";
import S6 from "../img/image3.jpg";
import T1 from '../img/team-1.jpg'
import T2 from "../img/team-2.jpg";
import T3 from "../img/team-3.jpg";
import T4 from "../img/team-4.jpg";
import R1 from '../img/testimonial-1.jpg'
import R2 from "../img/testimonial-2.jpg";
import R3 from "../img/testimonial-3.jpg";
import ContactForm from '@/Components/ContactForm'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div class="container-fluid p-0 mb-5">
				<div
					id="header-carousel"
					class="carousel slide"
					data-bs-ride="carousel"
				>
					<div class="carousel-inner">
						<div class="carousel-item active">
							<Image src={C1} />
							<div class="carousel-caption">
								<div class="container">
									<div class="row justify-content-center">
										<div class="col-lg-10 pt-5">
											<h1 class="display-4 text-white mb-4 animated slideInDown">
												Storm Accessories Car Window Tinting Dubai
											</h1>
											<p className="mb-4">
												CERAMIC COATING / PPF / OFFICE & HOME WINDOW TINTING /
												SAFETY & SECURITY FILM
											</p>
											<h2 class=" mb-4 pb-2 mx-sm-5 text-white text-[24px] leading-10 ">
												For high-quality window films that come in a wide range
												of styles and designs to offer privacy, safety, and sun
												protection, Storm Automotive LLC is a reputable name in
												the UAE. according to the UAE revised federal traffic
												law, which permits car windows to be tinted up to 50%
											</h2>
											<a
												href=""
												class="btn btn-primary py-3 px-5 animated slideInDown"
											>
												Book Me
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="carousel-item">
							<Image src={C2} />
							<div class="carousel-caption">
								<div class="container">
									<div class="row justify-content-center">
										<div class="col-lg-10 pt-5">
											<h1 class="display-4 text-white mb-4 animated slideInDown">
												Storm Accessories Car Window Tinting Dubai
											</h1>
											<p className="mb-4">
												CERAMIC COATING / PPF / OFFICE & HOME WINDOW TINTING /
												SAFETY & SECURITY FILM
											</p>
											<h2 class=" mb-4 pb-2 mx-sm-5 text-white text-[24px] leading-10 ">
												For high-quality window films that come in a wide range
												of styles and designs to offer privacy, safety, and sun
												protection, Storm Automotive LLC is a reputable name in
												the UAE. according to the UAE revised federal traffic
												law, which permits car windows to be tinted up to 50%
											</h2>
											<a
												href=""
												class="btn btn-primary py-3 px-5 animated slideInDown"
											>
												Call Now
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<button
						class="carousel-control-prev"
						type="button"
						data-bs-target="#header-carousel"
						data-bs-slide="prev"
					>
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button
						class="carousel-control-next"
						type="button"
						data-bs-target="#header-carousel"
						data-bs-slide="next"
					>
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div class="row g-5 align-items-center">
						<div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="h-100">
								<h1 class="display-6 mb-5 font-bold">
									BEST Storm Car Accessories CENTRE IN DUBAI
								</h1>

								<p class="mb-4 text-justify font-semibold">
									excessive UV rays, infrared radiation, sweltering heat, and
									glare by providing a wide range of car tinting in Dubai.
									Modern Auto Storm window films from us can offer improved
									comfort, security, and privacy. Being one of the top auto
									storm authorized center in the UAE, we are aware of the wide
									range of needs of our clients and offer them cutting-edge auto
									storm window films that satisfy their unique requirements for
									sun protection, lighting ergonomics, and temperature
									regulation. Our premium auto storm car tinting will assist in
									giving your automobile the required appearance and usefulness.
									Additionally, every one of our items has a scratch-resistant
									coating that ensures robustness and a flawless finish. You can
									take advantage of the wonderful health advantages of natural
									light and guard your home against excessive temperature
									changes with the help of our home tinting solution.
									Additionally, our auto storm car tint can enhance the comfort
									and luxury of a vehicle. Additionally, they provide a safe
									driving experience by reducing the excessive glare brought on
									by the sun or other man-made light sources.
								</p>
								<div class="border-top mt-4 pt-4">
									<div class="row">
										<div class="col-sm-6">
											<div class="d-flex align-items-center">
												<div class="btn-lg-square bg-primary rounded-circle me-3">
													<AiFillPhone color="#fff" />
												</div>
												<h5 class="mb-0">+012 345 6789</h5>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="d-flex align-items-center">
												<div class="btn-lg-square bg-primary rounded-circle me-3">
													<BsFillEnvelopeFill color="#ffff" />
												</div>
												<h5 class="mb-0">info@example.com</h5>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="row g-3">
								<div class="col-6 text-end">
									<div
										class="img-fluid w-75 wow zoomIn"
										style={{ marginTop: "25%" }}
									>
										<Image src={A1} />
									</div>
								</div>
								<div class="col-6 text-start">
									<div class="img-fluid w-100 wow zoomIn">
										<Image src={A2} />
									</div>
								</div>
								<div class="col-6 text-end">
									<div class="img-fluid w-50 wow zoomIn">
										<Image src={A3} />
									</div>
								</div>
								<div class="col-6 text-start">
									<div class="img-fluid w-75 wow zoomIn">
										<Image src={A4} />
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid   my-5 py-5 bgimage" data-parallax="scroll">
				<div class="container  py-5">
					<div class="row g-5  ">
						<div class="col-sm-6 col-lg-4 wow fadeIn" data-wow-delay="0.1s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								+500 Million
							</h1>
							<span class="text-primary">Happy Clients</span>
						</div>
						<div class="col-sm-6 col-lg-4 wow fadeIn" data-wow-delay="0.3s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								+200
							</h1>
							<span class="text-primary">Exper Team</span>
						</div>
						<div class="col-sm-6 col-lg-4 wow fadeIn" data-wow-delay="0.5s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								+385
							</h1>
							<span class="text-primary">Ongoing Project</span>
						</div>
					</div>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div
						class="text-center mx-auto wow fadeInUp"
						data-wow-delay="0.1s"
						style={{ maxWidth: "500px" }}
					>
						<h1 class="display-4 mb-3 ">OUR SERVICES</h1>
						<p className=" font-semibold leading-5 mb-5">
							Storm Automotive, a business known for its array of AUTO STORM
							auto tinting services in Dubai, is firmly committed to
							sustainability. We adopt a comprehensive approach to sun
							protection, damage avoidance, and glare reduction with our
							high-end window tinting and film services.
						</p>
					</div>
					<div class="row g-4 justify-content-center">
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S1} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Automotive
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S2} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Commercial Window Films
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S3} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Fasara
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S4} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Di-Noc
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S5} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Residential
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S6} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Safety & Security
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container py-5">
				<div class="">
					<div class="row g-5">
						<div class="col-lg-8 wow fadeInUp" data-wow-delay="0.1s">
							<h1 class="display-6 mb-2 font-bold">
								WHY TO CHOOSE Storm AUTOMOTIVE ?
							</h1>
							<h2 className="font-bold text-[24px]">CAR TINTING IN DUBAI</h2>
							<p class="mb-5 text-justify font-semibold">
								With its excellent quality auto storm car tinting in Dubai,
								window film, Storm Automotive LLC has improved and transformed
								many vehicles and structures since its founding in 2010. To
								improve energy efficiency, safety, and general privacy, our
								highly qualified team of professionals can offer efficient
								window tinting services for cars and homes. Customers have the
								highest faith in us for a number of reasons. Several of them are
								listed below.
							</p>
							<div className="row">
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiShakingHands size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">World-class products</h5>
											<p className="text-justify font-semibold">
												Storm Automotive offers a wide selection of window films
												as an authorised Storm accessories tinting centre in
												Dubai. All of our goods come from a high-quality company
												that is the industry leader in window film production.
												Additionally, they have completed a number of quality
												analysis procedures to guarantee unrivalled quality.
												These window tinting options seek to provide a safer
												driving environment by minimising glare. Additionally,
												they can offer the required level of safety and defence
												against damaging sunrays when used on a window.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiAchievement size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">
												Extensive Industry Experience
											</h5>
											<p className="text-justify font-semibold">
												With around 20 years of car-tinting experience in Dubai,
												we aim to continually provide perfection. All window
												tinting services can be performed by our skilled
												personnel with the utmost precision. These professionals
												can polish and detail any vehicle to a high standard and
												within the allotted time thanks to their attention to
												detail. Additionally, they continue to expand their
												knowledge and skills as automobile tinting technology
												advances.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiCombinationLock size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">Authorization</h5>
											<p className="text-justify font-semibold">
												Storm Automotive relies on ethical business practises
												and standards because it is an authorised partner of the
												top manufacturer of sun control window films in the
												world. We go above and above to establish a connection
												of trust with our customers. Therefore, each car tinting
												service or product provided by our business includes an
												authenticity certificate.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<FcApproval size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">
												Scientifically-approved window films
											</h5>
											<p className="text-justify font-semibold">
												As a licenced window film dealer, storm Automotive
												offers premium automobile tinting products with some
												known health advantages. These cutting-edge storm car
												tints have been validated by science and can block up to
												99% of UV and infrared rays. As a result of their
												prolonged sun exposure, they shield themselves from
												prevalent ailments.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiThreeFriends size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">Budget-friendly</h5>
											<p className="text-justify font-semibold">
												We dont demand that you spend a fortune protecting your
												car from dangerous UV and infrared rays. Instead, we
												provide affordable auto tinting and sun control window
												films to improve comfort. We also offer a variety of
												solutions for home tinting and let our customers select
												the one that best suits their needs and their budget.
												Additionally, our window tinting options can enable you
												to reduce your long-term lighting and air conditioning
												expenses.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiShakingHands size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">100% Satisfaction</h5>
											<p className="text-justify font-semibold">
												At Storm Automotive, we perform superior storm auto
												tinting services in Dubai and around the UAE with the
												goal of achieving unmatched client satisfaction. We
												guarantee that our goods will meet your expectations for
												quality and performance. Additionally, they maintain
												their appearance and colour throughout time.
												Additionally, being a reputable window tinting business
												in the UAE, we continuously adapt to meet the shifting
												needs and preferences of our clients.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 wow fadeInUp" data-wow-delay="0.5s">
							<div
								class="position-relative rounded overflow-hidden h-100"
								style={{ minHeight: "400px" }}
							>
								<div
									class="position-absolute w-100 h-100"
									style={{ objectFit: "cover;" }}
								>
									<Image src={Feature} />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className="bgimage2 py-28 mt-5">
				<div className="row container">
					<div className="col-md-6">
						<h1 className="text-center text-[44px] text-white font-bold">
							CALL US FOR LIVE ASSISTANCE
						</h1>
						<h2 className="text-center text-[28px] text-white font-semibold">
							Its time to turn to our experts for assignment
						</h2>
					</div>
					<div className="col-md-6">
						<a className="btn btn-primary lg:ml-52  mt-4 inline-flex px-10">
							{" "}
							<FiPhoneCall size={20} style={{ marginRight: "10px" }} /> Call Now
						</a>
					</div>
				</div>
			</div>
			<div className="container">
				<h1 className="text-center text-[44px] font-bold mb-5">GUARANTEES</h1>
				<h2 className="text-center text-[20px] mb-2 font-semibold">
					In the UAE, storm Automotive is a reliable source of tint and provides
					some of the best warranties available.
				</h2>
				<h2 className="text-center text-[20px] mb-2 font-semibold">
					Protection against colour fading We guarantee that all of our window
					films wont fade for years, and that both intense wind and direct
					sunlight wont dull their glossy sheen.
				</h2>
				<div className="row mt-10">
					<div className="col-md-4">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top  mt-5">
								<BsShieldCheck size={50} style={{ marginLeft: "45%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] font-bold">
									Warranty for UV ray blockage
								</h5>
								<p class="card-text text-justify">
									The window/car tints from Storm Automotive offer some UV and
									infrared radiation protection. They will therefore let you to
									enjoy natural sunshine without having to deal with its
									negative consequences.
								</p>
							</div>
						</div>
					</div>
					<div className="col-md-4">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top  mt-5">
								<GiFactory size={50} style={{ marginLeft: "45%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] font-bold">
									Industry’s leading warranties
								</h5>
								<p class="card-text text-justify">
									Our contemporary window films offer all the advantages
									outlined by industry standards. Additionally, they come with a
									warranty against delamination, peeling, blistering, and
									bubbling. They are non-metallic, so they dont affect how
									mobile devices and satellite communications normally operate.
								</p>
							</div>
						</div>
					</div>
					<div className="col-md-4">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top mt-5">
								<GiMetalDisc size={50} style={{ marginLeft: "45%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] font-bold">
									Warranty for non-metallic window films
								</h5>
								<p class="card-text text-justify">
									Our contemporary automobile window films do not include any
									metallic components, in contrast to their conventional
									equivalents. As a result, they dont prevent mobile devices and
									satellite signals from operating normally.
								</p>
							</div>
						</div>
					</div>
				</div>
				<p className="mt-8 font-semibold text-justify">
					In addition to adhering to the many quality standards established by
					the new Federal Traffic Law that went into effect on July 1st, we also
					follow an universal installation guideline. Additionally, we back up
					the same with a few warranties that come with each window film.
					<br /> If it turns out that our product is flawed, we will replace it
					at no additional cost. You will need to provide the purchase receipt,
					which includes information on the kind of film and the installation
					date, in order to take advantage of the guarantee. The length of the
					guarantee may differ depending on the particular automobile or window
					tint you have selected. The following warranties are provided to our
					clients.
				</p>
			</div>
			<div className=" bgimage">
				<h1 className="text-center text-white text-[32px] font-bold">
					HOW IT WORKS
				</h1>
				<div className="row container py-28 m-auto">
					<div className="col-md-3">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top   mt-5">
								<BsPeople size={100} style={{ marginLeft: "35%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] text-center font-bold">
									MEET THE CLIENT
								</h5>
							</div>
						</div>
					</div>
					<div className="col-md-3">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top  mt-5">
								<GrUserWorker size={100} style={{ marginLeft: "35%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] text-center font-bold">
									CUSTOMISE SOLUTION
								</h5>
							</div>
						</div>
					</div>
					<div className="col-md-3">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top  mt-5">
								<GrUnorderedList size={100} style={{ marginLeft: "35%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] text-center font-bold">
									CONFIRM ORDER
								</h5>
							</div>
						</div>
					</div>
					<div className="col-md-3">
						<div class="card" style={{ width: "18rem" }}>
							<div class="card-img-top  mt-5">
								<GrDeliver size={100} style={{ marginLeft: "35%" }} />
							</div>

							<div class="card-body">
								<h5 class="card-title text-[18px] text-center font-bold">
									DELIVERY & INSTALLATION
								</h5>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className=" mt-10">
				<div className="container m-auto">
					<h1 className="font-bold text-[44px]">
						STORM AUTOMATIVE WINDOW FILM AND CAR TINTING CENTER SHARJAH
					</h1>
					<h2 className="font-semibold text-[20px] text-justify mt-5 mb-5 leading-8">
						WINDOW TINTING CAN OFFER LONG-LASTING PRACTICAL ADVANTAGES, SUCH AS
						PRIVACY, SUN PROTECTION, AND SAFETY, IN ADDITION TO IMPROVING
						AESTHETICS. STORM AUTOMOTIVE IS A REPUTABLE AUTO TINTING BUSINESS
						THAT WORKS WITH YOU TO INSTALL AN OPTICALLY TRANSPARENT FILM TO GIVE
						VEHICLES THE PERFORMANCE AND APPEARANCE YOU WANT. ALL OF OUR
						MATERIALS PROTECT AGAINST UV RADIATION AND ADHERE TO UAE AUTOMOBILE
						TINTING REGULATIONS. ADDITIONALLY, THEY INCLUDE A UV PROTECTION
						CERTIFICATION THAT YOU CAN ATTEST TO.
					</h2>
					<div class="accordion" id="accordionExample">
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingOne">
								<button
									class="accordion-button"
									type="button"
									data-bs-toggle="collapse"
									data-bs-target="#collapseOne"
									aria-expanded="true"
									aria-controls="collapseOne"
								>
									Trusted Window Tinting Centre in Dubai
								</button>
							</h2>
							<div
								id="collapseOne"
								class="accordion-collapse collapse show"
								aria-labelledby="headingOne"
								data-bs-parent="#accordionExample"
							>
								<div class="accordion-body text-justify">
									Window films are an excellent investment since they offer
									everything from temperature control to sun protection. Optical
									clear films may be installed by Storm Automotive, a reputable
									window tinting business, to safeguard your car and provide you
									with a safer and more pleasant ride. We have a wide variety of
									automobile tints to comply with the new traffic regulation in
									Dubai, which permits car owners to receive up to 50% tint.
									<br />
									<br />
									Your automobile may have a brand-new appearance thanks to our
									high-quality window tinting services. We can provide you with
									the ideal window/car tinting solution, regardless of whether
									you need a specific amount of UV protection, light filtering,
									interior upgrading, privacy, safety, or glare relief. Our
									staff considers each customers particular needs and offers the
									best window tinting materials to fit them.
								</div>
							</div>
						</div>
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingTwo">
								<button
									class="accordion-button collapsed"
									type="button"
									data-bs-toggle="collapse"
									data-bs-target="#collapseTwo"
									aria-expanded="false"
									aria-controls="collapseTwo"
								>
									Upgrade the Style and Comfort of Your Vehicle with storm
									Window Tinting
								</button>
							</h2>
							<div
								id="collapseTwo"
								class="accordion-collapse collapse"
								aria-labelledby="headingTwo"
								data-bs-parent="#accordionExample"
							>
								<div class="accordion-body text-justify">
									We try to satisfy the various demands of automobile owners in
									the UAE with our premium automotive window tinting, which
									exudes unrivalled excellence. We provide you with a wide range
									of automobile tinting choices that enable you to drive more
									easily, including Crystalline, Ceramic Coating, and FX Series.
									Simply inform us of your issues, and our window tinting
									specialists will respond with appropriate advice. We will
									implement a product or service when you approve it.
								</div>
							</div>
						</div>
						<div class="accordion-item">
							<h2 class="accordion-header" id="headingThree">
								<button
									class="accordion-button collapsed"
									type="button"
									data-bs-toggle="collapse"
									data-bs-target="#collapseThree"
									aria-expanded="false"
									aria-controls="collapseThree"
								>
									An Exhaustive Range of Car Window Tinting Services
								</button>
							</h2>
							<div
								id="collapseThree"
								class="accordion-collapse collapse"
								aria-labelledby="headingThree"
								data-bs-parent="#accordionExample"
							>
								<div class="accordion-body">
									Storm automotive, a window tinting company with years of
									expertise, offers a wide range of automobile and window
									tinting choices in dubai. Therefore, you may choose a window
									film that suits your needs here, whether you want privacy and
									protection or a better look. We make sure that all of our
									products are made to offer uv protection, reduce overheating,
									and the required amount of privacy since we are an approved
									storm vehicle tinting facility in dubai.
									<br /> In addition to providing products of the highest
									calibre, our business places a huge emphasis on appropriate
									installation and finishing. Additionally, as an approved
									automobile tinting shop, we provide a wide array of services,
									including
									<br />
									<span className="text-red-600">Car Window Tinting </span>
									<br />
									Our premium selection of storm sun control films gives the
									inside of your automobile the necessary degree of privacy and
									security..
									<br />
									<span className="text-red-600">
										Creative Vehicle Graphics{" "}
									</span>
									<br />
									As a storm certified car tinting shop in Dubai, we give you
									countless opportunities to express your creativity via vehicle
									wraps.
									<br />
									<span className="text-red-600">Paint Protection Film </span>
									<br />
									When used on a cars painted surfaces, this high-end automobile
									tinting aids in avoiding fading or abrasion.
									<br />
									<span className="text-red-600">Car Detailing </span>
									<br />
									With a range of services, we can provide a brand-new look to
									the interior and exterior of your car.
									<br />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<ContactForm/>
		</>
	);
}
