import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import C1 from '../img/window-tinting-2.jpg'
import C2 from '../img/carousel-2.jpg'
import Icon7 from '../img/icon/icon-07-primary.png'
import Icon9 from "../img/icon/icon-09-primary.png";
import Icon8 from "../img/icon/icon-08-light.png";
import Icon10 from "../img/icon/icon-10-light.png";
import Icon6 from "../img/icon/icon-06-light.png";
import Icon1 from "../img/icon/icon-01-light.png";
import Icon2 from "../img/icon/icon-02-light.png";
import Icon3 from "../img/icon/icon-03-light.png";
import Icon4 from "../img/icon/icon-04-light.png";
import Icon5 from "../img/icon/icon-05-light.png";
import {
	GiShakingHands,
	GiAchievement,
	GiCombinationLock,
	GiThreeFriends,
} from "react-icons/gi";
import {FcApproval} from 'react-icons/fc'

import A1 from '../img/about-1.jpg'
import A2 from "../img/about-2.jpg";
import A3 from "../img/about-3.jpg";
import A4 from "../img/about-4.jpg";
import { AiFillPhone } from "react-icons/ai";
import { BsFillEnvelopeFill } from "react-icons/bs";
import Feature from '../img/why-us-img.png'
import S1 from '../img/service-1.jpg'
import S2 from "../img/service-2.jpg";
import S3 from "../img/service-3.jpg";
import S4 from "../img/image.jpg";
import S5 from "../img/image2.jpg";
import S6 from "../img/image3.jpg";
import T1 from '../img/team-1.jpg'
import T2 from "../img/team-2.jpg";
import T3 from "../img/team-3.jpg";
import T4 from "../img/team-4.jpg";
import R1 from '../img/testimonial-1.jpg'
import R2 from "../img/testimonial-2.jpg";
import R3 from "../img/testimonial-3.jpg";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div class="container-fluid p-0 mb-5">
				<div
					id="header-carousel"
					class="carousel slide"
					data-bs-ride="carousel"
				>
					<div class="carousel-inner">
						<div class="carousel-item active">
							<Image src={C1} />
							<div class="carousel-caption">
								<div class="container">
									<div class="row justify-content-center">
										<div class="col-lg-10 pt-5">
											<h1 class="display-4 text-white mb-4 animated slideInDown">
												Storm Accessories Car Window Tinting Dubai
											</h1>
											<p className="mb-4">
												CERAMIC COATING / PPF / OFFICE & HOME WINDOW TINTING /
												SAFETY & SECURITY FILM
											</p>
											<h2 class=" mb-4 pb-2 mx-sm-5 text-white text-[24px] leading-10 ">
												For high-quality window films that come in a wide range
												of styles and designs to offer privacy, safety, and sun
												protection, Storm Automotive LLC is a reputable name in
												the UAE. according to the UAE revised federal traffic
												law, which permits car windows to be tinted up to 50%
											</h2>
											<a
												href=""
												class="btn btn-primary py-3 px-5 animated slideInDown"
											>
												Explore More
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="carousel-item">
							<Image src={C2} />
							<div class="carousel-caption">
								<div class="container">
									<div class="row justify-content-center">
										<div class="col-lg-10 pt-5">
											<h1 class="display-4 text-white mb-4 animated slideInDown">
												Storm Accessories Car Window Tinting Dubai
											</h1>
											<p className="mb-4">
												CERAMIC COATING / PPF / OFFICE & HOME WINDOW TINTING /
												SAFETY & SECURITY FILM
											</p>
											<h2 class=" mb-4 pb-2 mx-sm-5 text-white text-[24px] leading-10 ">
												For high-quality window films that come in a wide range
												of styles and designs to offer privacy, safety, and sun
												protection, Storm Automotive LLC is a reputable name in
												the UAE. according to the UAE revised federal traffic
												law, which permits car windows to be tinted up to 50%
											</h2>
											<a
												href=""
												class="btn btn-primary py-3 px-5 animated slideInDown"
											>
												Explore More
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<button
						class="carousel-control-prev"
						type="button"
						data-bs-target="#header-carousel"
						data-bs-slide="prev"
					>
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button
						class="carousel-control-next"
						type="button"
						data-bs-target="#header-carousel"
						data-bs-slide="next"
					>
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div class="row g-5 align-items-center">
						<div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="h-100">
								<h1 class="display-6 mb-5 font-bold">
									BEST Storm Car Accessories CENTRE IN DUBAI
								</h1>

								<p class="mb-4 text-justify font-semibold">
									excessive UV rays, infrared radiation, sweltering heat, and
									glare by providing a wide range of car tinting in Dubai.
									Modern Auto Storm window films from us can offer improved
									comfort, security, and privacy. Being one of the top auto
									storm authorized center in the UAE, we are aware of the wide
									range of needs of our clients and offer them cutting-edge auto
									storm window films that satisfy their unique requirements for
									sun protection, lighting ergonomics, and temperature
									regulation. Our premium auto storm car tinting will assist in
									giving your automobile the required appearance and usefulness.
									Additionally, every one of our items has a scratch-resistant
									coating that ensures robustness and a flawless finish. You can
									take advantage of the wonderful health advantages of natural
									light and guard your home against excessive temperature
									changes with the help of our home tinting solution.
									Additionally, our auto storm car tint can enhance the comfort
									and luxury of a vehicle. Additionally, they provide a safe
									driving experience by reducing the excessive glare brought on
									by the sun or other man-made light sources.
								</p>
								<div class="border-top mt-4 pt-4">
									<div class="row">
										<div class="col-sm-6">
											<div class="d-flex align-items-center">
												<div class="btn-lg-square bg-primary rounded-circle me-3">
													<AiFillPhone color="#fff" />
												</div>
												<h5 class="mb-0">+012 345 6789</h5>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="d-flex align-items-center">
												<div class="btn-lg-square bg-primary rounded-circle me-3">
													<BsFillEnvelopeFill color="#ffff" />
												</div>
												<h5 class="mb-0">info@example.com</h5>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="row g-3">
								<div class="col-6 text-end">
									<div
										class="img-fluid w-75 wow zoomIn"
										style={{ marginTop: "25%" }}
									>
										<Image src={A1} />
									</div>
								</div>
								<div class="col-6 text-start">
									<div class="img-fluid w-100 wow zoomIn">
										<Image src={A2} />
									</div>
								</div>
								<div class="col-6 text-end">
									<div class="img-fluid w-50 wow zoomIn">
										<Image src={A3} />
									</div>
								</div>
								<div class="col-6 text-start">
									<div class="img-fluid w-75 wow zoomIn">
										<Image src={A4} />
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid  my-5 py-5 bgimage" data-parallax="scroll">
				<div class="container py-5">
					<div class="row g-5">
						<div class="col-sm-6 col-lg-3 wow fadeIn" data-wow-delay="0.1s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								1234
							</h1>
							<span class="text-primary">Happy Clients</span>
						</div>
						<div class="col-sm-6 col-lg-3 wow fadeIn" data-wow-delay="0.3s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								1234
							</h1>
							<span class="text-primary">Projects Succeed</span>
						</div>
						<div class="col-sm-6 col-lg-3 wow fadeIn" data-wow-delay="0.5s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								1234
							</h1>
							<span class="text-primary">Awards Achieved</span>
						</div>
						<div class="col-sm-6 col-lg-3 wow fadeIn" data-wow-delay="0.7s">
							<h1 class="display-4 text-white" data-toggle="counter-up">
								1234
							</h1>
							<span class="text-primary">Team Members</span>
						</div>
					</div>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div
						class="text-center mx-auto wow fadeInUp"
						data-wow-delay="0.1s"
						style={{ maxWidth: "500px" }}
					>
						<h1 class="display-4 mb-3 ">OUR SERVICES</h1>
						<p className=" font-semibold leading-5 mb-5">
							Storm Automotive, a business known for its array of AUTO STORM
							auto tinting services in Dubai, is firmly committed to
							sustainability. We adopt a comprehensive approach to sun
							protection, damage avoidance, and glare reduction with our
							high-end window tinting and film services.
						</p>
					</div>
					<div class="row g-4 justify-content-center">
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S1} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Automotive
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S2} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Commercial Window Films
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S3} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Fasara
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S4} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Di-Noc
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S5} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Residential
									</a>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="service-item">
								<div class="img-fluid">
									<Image src={S6} />
								</div>
								<div class="d-flex align-items-center bg-light">
									<a class="h4 mx-4 mb-0" href="">
										Safety & Security
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container py-5">
				<div class="">
					<div class="row g-5">
						<div class="col-lg-8 wow fadeInUp" data-wow-delay="0.1s">
							<h1 class="display-6 mb-2 font-bold">
								WHY TO CHOOSE Storm AUTOMOTIVE ?
							</h1>
							<h2 className="font-bold text-[24px]">CAR TINTING IN DUBAI</h2>
							<p class="mb-5 text-justify font-semibold">
								With its excellent quality auto storm car tinting in Dubai,
								window film, Storm Automotive LLC has improved and transformed
								many vehicles and structures since its founding in 2010. To
								improve energy efficiency, safety, and general privacy, our
								highly qualified team of professionals can offer efficient
								window tinting services for cars and homes. Customers have the
								highest faith in us for a number of reasons. Several of them are
								listed below.
							</p>
							<div className="row">
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiShakingHands size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">World-class products</h5>
											<p className="text-justify font-semibold">
												Storm Automotive offers a wide selection of window films
												as an authorised Storm accessories tinting centre in
												Dubai. All of our goods come from a high-quality company
												that is the industry leader in window film production.
												Additionally, they have completed a number of quality
												analysis procedures to guarantee unrivalled quality.
												These window tinting options seek to provide a safer
												driving environment by minimising glare. Additionally,
												they can offer the required level of safety and defence
												against damaging sunrays when used on a window.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiAchievement size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">
												Extensive Industry Experience
											</h5>
											<p className="text-justify font-semibold">
												With around 20 years of car-tinting experience in Dubai,
												we aim to continually provide perfection. All window
												tinting services can be performed by our skilled
												personnel with the utmost precision. These professionals
												can polish and detail any vehicle to a high standard and
												within the allotted time thanks to their attention to
												detail. Additionally, they continue to expand their
												knowledge and skills as automobile tinting technology
												advances.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiCombinationLock size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">Authorization</h5>
											<p className="text-justify font-semibold">
												Storm Automotive relies on ethical business practises
												and standards because it is an authorised partner of the
												top manufacturer of sun control window films in the
												world. We go above and above to establish a connection
												of trust with our customers. Therefore, each car tinting
												service or product provided by our business includes an
												authenticity certificate.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<FcApproval size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">
												Scientifically-approved window films
											</h5>
											<p className="text-justify font-semibold">
												As a licenced window film dealer, storm Automotive
												offers premium automobile tinting products with some
												known health advantages. These cutting-edge storm car
												tints have been validated by science and can block up to
												99% of UV and infrared rays. As a result of their
												prolonged sun exposure, they shield themselves from
												prevalent ailments.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiThreeFriends size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">Budget-friendly</h5>
											<p className="text-justify font-semibold">
												We dont demand that you spend a fortune protecting your
												car from dangerous UV and infrared rays. Instead, we
												provide affordable auto tinting and sun control window
												films to improve comfort. We also offer a variety of
												solutions for home tinting and let our customers select
												the one that best suits their needs and their budget.
												Additionally, our window tinting options can enable you
												to reduce your long-term lighting and air conditioning
												expenses.
											</p>
										</div>
									</div>
								</div>
								<div className="col-md-5">
									<div class="d-flex mb-5">
										<div
											class="flex-shrink-0 btn-square bg-primary rounded-circle"
											style={{ width: "90px", height: "90px" }}
										>
											<div class="img-fluid">
												<GiShakingHands size={40} color="#ffff" />
											</div>
										</div>
										<div class="ms-4">
											<h5 class="mb-3 font-bold">100% Satisfaction</h5>
											<p className="text-justify font-semibold">
												At Storm Automotive, we perform superior storm auto
												tinting services in Dubai and around the UAE with the
												goal of achieving unmatched client satisfaction. We
												guarantee that our goods will meet your expectations for
												quality and performance. Additionally, they maintain
												their appearance and colour throughout time.
												Additionally, being a reputable window tinting business
												in the UAE, we continuously adapt to meet the shifting
												needs and preferences of our clients.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-4 wow fadeInUp" data-wow-delay="0.5s">
							<div
								class="position-relative rounded overflow-hidden h-100"
								style={{ minHeight: "400px" }}
							>
								<div
									class="position-absolute w-100 h-100"
									style={{ objectFit: "cover;" }}
								>
									<Image src={Feature} />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid overflow-hidden my-5 px-lg-0">
				<div class="container quote px-lg-0 bgimage">
					<div class="row g-0 mx-lg-0">
						<div class="col-lg-6 quote-text ">
							<div
								class="h-100 px-4 px-sm-5 ps-lg-0 wow fadeIn"
								data-wow-delay="0.1s"
							>
								<h1 class="text-white mb-4">
									For Individuals And Organisations
								</h1>
								<p class="text-light mb-5">
									Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit.
									Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit,
									sed stet lorem sit clita duo justo magna dolore erat amet
								</p>
								<a href="" class="align-self-start btn btn-primary py-3 px-5">
									More Details
								</a>
							</div>
						</div>
						<div class="col-lg-6 quote-form bgimage" data-parallax="scroll">
							<div
								class="h-100 px-4 px-sm-5 pe-lg-0 wow fadeIn"
								data-wow-delay="0.5s"
							>
								<div class="bg-white p-4 p-sm-5">
									<div class="row g-3">
										<div class="col-sm-6">
											<div class="form-floating">
												<input
													type="text"
													class="form-control"
													id="gname"
													placeholder="Gurdian Name"
												/>
												<label for="gname">Your Name</label>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="form-floating">
												<input
													type="email"
													class="form-control"
													id="gmail"
													placeholder="Gurdian Email"
												/>
												<label for="gmail">Your Email</label>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="form-floating">
												<input
													type="text"
													class="form-control"
													id="cname"
													placeholder="Child Name"
												/>
												<label for="cname">Your Mobile</label>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="form-floating">
												<input
													type="text"
													class="form-control"
													id="cage"
													placeholder="Child Age"
												/>
												<label for="cage">Service Type</label>
											</div>
										</div>
										<div class="col-12">
											<div class="form-floating">
												<textarea
													class="form-control"
													placeholder="Leave a message here"
													id="message"
													style={{ height: "80px" }}
												></textarea>
												<label for="message">Message</label>
											</div>
										</div>
										<div class="col-12">
											<button class="btn  py-3 px-5" type="submit">
												Get A Free Quote
											</button>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div
						class="text-center mx-auto wow fadeInUp"
						data-wow-delay="0.1s"
						style={{ maxWidth: "500px" }}
					>
						<h1 class="display-6 mb-5">Meet Our Professional Team Members</h1>
					</div>
					<div class="row g-4">
						<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
							<div class="team-item">
								<div class="team-img position-relative overflow-hidden">
									<div class="img-fluid">
										<Image src={T1} alt="" />
									</div>

									<div class="team-social">
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-facebook-f"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-twitter"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-instagram"></i>
										</a>
									</div>
								</div>
								<div class="bg-light text-center p-4">
									<h5>Full Name</h5>
									<span class="text-primary">Designation</span>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
							<div class="team-item">
								<div class="team-img position-relative overflow-hidden">
									<div class="img-fluid">
										<Image src={T2} alt="" />
									</div>
									<div class="team-social">
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-facebook-f"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-twitter"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-instagram"></i>
										</a>
									</div>
								</div>
								<div class="bg-light text-center p-4">
									<h5>Full Name</h5>
									<span class="text-primary">Designation</span>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
							<div class="team-item">
								<div class="team-img position-relative overflow-hidden">
									<div class="img-fluid">
										<Image src={T3} alt="" />
									</div>
									<div class="team-social">
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-facebook-f"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-twitter"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-instagram"></i>
										</a>
									</div>
								</div>
								<div class="bg-light text-center p-4">
									<h5>Full Name</h5>
									<span class="text-primary">Designation</span>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">
							<div class="team-item">
								<div class="team-img position-relative overflow-hidden">
									<div class="img-fluid">
										<Image src={T4} alt="" />
									</div>
									<div class="team-social">
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-facebook-f"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-twitter"></i>
										</a>
										<a
											class="btn btn-square btn-primary rounded-circle m-1"
											href=""
										>
											<i class="fab fa-instagram"></i>
										</a>
									</div>
								</div>
								<div class="bg-light text-center p-4">
									<h5>Full Name</h5>
									<span class="text-primary">Designation</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-xxl py-5">
				<div class="container">
					<div
						class="text-center mx-auto wow fadeInUp"
						data-wow-delay="0.1s"
						style={{ maxWidth: "500px" }}
					>
						<h1 class="display-6 mb-5">What They Say About Our Services</h1>
					</div>
					<div
						id="carouselExampleCaptions"
						class="carousel slide relative carousel-dark"
						data-bs-ride="carousel"
					>
						<div class="carousel-inner relative w-full overflow-hidden">
							<div class="carousel-item active relative float-left w-full">
								<div class="">
									<Image
										style={{
											borderRadius: "9999px",
											marginLeft: "auto",
											marginRight: "auto",
										}}
										src={R1}
										alt="avatar"
										width={150}
										height={150}
									/>
								</div>
								<div class="flex flex-wrap justify-center">
									<div class="grow-0 shrink-0 basis-auto w-full lg:w-8/12 px-3">
										<h5 class="text-lg font-bold mb-3">Hassan Tariq</h5>

										<p class="text-gray-500 mb-6">
											<svg
												aria-hidden="true"
												focusable="false"
												data-prefix="fas"
												data-icon="quote-left"
												class="w-6 pr-2 inline-block"
												role="img"
												xmlns="http://www.w3.org/2000/svg"
												viewBox="0 0 512 512"
											>
												<path
													fill="currentColor"
													d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z"
												></path>
											</svg>
											I think this is a fantastic farm in our area, with
											excellent work being done.
										</p>
										<ul class="flex justify-center mb-0">
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="far"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M528.1 171.5L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6zM388.6 312.3l23.7 138.4L288 385.4l-124.3 65.3 23.7-138.4-100.6-98 139-20.2 62.2-126 62.2 126 139 20.2-100.6 98z"
													></path>
												</svg>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="carousel-item relative float-left w-full">
								<Image
									style={{
										borderRadius: "9999px",
										marginLeft: "auto",
										marginRight: "auto",
									}}
									src={R2}
									alt="avatar"
									width={150}
									height={150}
								/>
								<div class="flex flex-wrap justify-center">
									<div class="grow-0 shrink-0 basis-auto w-full lg:w-8/12 px-3">
										<h5 class="text-lg font-bold mb-3">Mujeeb Khan</h5>

										<p class="text-gray-500 mb-6">
											<svg
												aria-hidden="true"
												focusable="false"
												data-prefix="fas"
												data-icon="quote-left"
												class="w-6 pr-2 inline-block"
												role="img"
												xmlns="http://www.w3.org/2000/svg"
												viewBox="0 0 512 512"
											>
												<path
													fill="currentColor"
													d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z"
												></path>
											</svg>
											Excellent service, good quality and amount of oranges.
										</p>
										<ul class="flex justify-center mb-0">
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star-half-alt"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 536 512"
												>
													<path
														fill="currentColor"
														d="M508.55 171.51L362.18 150.2 296.77 17.81C290.89 5.98 279.42 0 267.95 0c-11.4 0-22.79 5.9-28.69 17.81l-65.43 132.38-146.38 21.29c-26.25 3.8-36.77 36.09-17.74 54.59l105.89 103-25.06 145.48C86.98 495.33 103.57 512 122.15 512c4.93 0 10-1.17 14.87-3.75l130.95-68.68 130.94 68.7c4.86 2.55 9.92 3.71 14.83 3.71 18.6 0 35.22-16.61 31.66-37.4l-25.03-145.49 105.91-102.98c19.04-18.5 8.52-50.8-17.73-54.6zm-121.74 123.2l-18.12 17.62 4.28 24.88 19.52 113.45-102.13-53.59-22.38-11.74.03-317.19 51.03 103.29 11.18 22.63 25.01 3.64 114.23 16.63-82.65 80.38z"
													></path>
												</svg>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="carousel-item relative float-left w-full">
								<Image
									style={{
										borderRadius: "9999px",
										marginLeft: "auto",
										marginRight: "auto",
									}}
									src={R3}
									alt="avatar"
									width={150}
									height={150}
								/>
								<div class="flex flex-wrap justify-center">
									<div class="grow-0 shrink-0 basis-auto w-full lg:w-8/12 px-3">
										<h5 class="text-lg font-bold mb-3">Shoaib Khan</h5>

										<p class="text-gray-500 mb-6">
											<svg
												aria-hidden="true"
												focusable="false"
												data-prefix="fas"
												data-icon="quote-left"
												class="w-6 pr-2 inline-block"
												role="img"
												xmlns="http://www.w3.org/2000/svg"
												viewBox="0 0 512 512"
											>
												<path
													fill="currentColor"
													d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z"
												></path>
											</svg>
											They are delivering this excellent product to peoples
											homes.
										</p>
										<ul class="flex justify-center mb-0">
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
											<li>
												<svg
													aria-hidden="true"
													focusable="false"
													data-prefix="fas"
													data-icon="star"
													class="w-4 text-yellow-500"
													role="img"
													xmlns="http://www.w3.org/2000/svg"
													viewBox="0 0 576 512"
												>
													<path
														fill="currentColor"
														d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
													></path>
												</svg>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<button
							class="carousel-control-prev absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline left-0"
							type="button"
							data-bs-target="#carouselExampleCaptions"
							data-bs-slide="prev"
						>
							<span
								class="carousel-control-prev-icon inline-block bg-no-repeat"
								aria-hidden="true"
							></span>
							<span class="visually-hidden">Previous</span>
						</button>
						<button
							class="carousel-control-next absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline right-0"
							type="button"
							data-bs-target="#carouselExampleCaptions"
							data-bs-slide="next"
						>
							<span
								class="carousel-control-next-icon inline-block bg-no-repeat"
								aria-hidden="true"
							></span>
							<span class="visually-hidden">Next</span>
						</button>
					</div>
				</div>
			</div>
			/
		</>
	);
}
